### ISSUE TITLE
Google Login Problem

### ISSUE THREAD

**Issue by gutosantos82** [gutosantos82/dance#2]
When I use the login button on my mobile, the login button doesn't hide and the this.email is not updated with my email.

**Comment by heukirne** [comment]
Pra mim tá funcionando. Coloquei um campo visível de email pra ver se funciona no teu,

**Comment by gutosantos82** [comment]
No teu o botao de login some?

**Comment by heukirne** [comment]
sim.
faz um teste, clica no login, espera um tempo e depois clica no menu
as vezes só atualiza depois de uma ação, 
se for isso, tem que colocar o zone.run no logged = true
